### PR TITLE
fix BitSet(0).flip().msb()

### PR DESCRIPTION
**Pull request by laszlokorte**
`BitSet(0).flip().msb()` causes an infinity loop because arithmetic shift is used.

This fixes it by using logic shift instead.

### CODE REVIEW

**Comment by infusion** [comment]
I think I accepted your pull-requests in the wrong order, so github wasn't able to merge it. Doing it on my own wasn't possible due to a 403 error on github. I pushed the fix on my own. Please update your fork as well.

Thanks a lot for this fix!

**Comment by laszlokorte** [comment]
Thank you

**Comment by laszlokorte** [comment]
Are you going to release a new version containing this fix? I would like to remove the monkey patch from my project.

**Comment by infusion** [comment]
3.1.0 landed. Sorry, I just came back home and merged it on the road.

**Comment by laszlokorte** [comment]
Awesome, thank you!

**Pull request closed without merging**
